const express=require("express")
const userRoutes=require("./route/user.js")
const ngoRoutes=require("./route/organization.js")
const connectDB=require("./util/db.js")
const cors=require("cors")
require("dotenv").config()
connectDB()
const app=express()
app.use(cors())
app.use(express.json())
app.use("/api/v1/users", userRoutes)
app.use("/api/v1/ngos", ngoRoutes)
app.listen(process.env.PORT_NUMBER, ()=>{
    console.log(`Server running at ${process.env.PORT_NUMBER}`)
})