const router=require("express").Router()
const {isAuth}=require("../middleware/isAuth")
const {getUsers, getUser, createUser, updateUser, deleteUser, loginUser, changeUserType}=require("../controller/user")
router.get("/", getUsers)
router.get("/:id", getUser)
router.post("/", createUser)
router.post("/login", loginUser)
router.put("/", isAuth, updateUser)
router.delete("/:id", isAuth, deleteUser)
router.patch("/:id", isAuth, changeUserType)
module.exports=router